
trigger:
- master



# strategy:
#   matrix:
#    linux:
#      operatingSystem: 'ubuntu-latest'
#    mac:
#      operatingSystem: 'macos-latest'
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
  - job: Buildjob
    steps:
    - bash: echo "Do the build"
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: Deploy on Dev
- stage: QADeploy
  jobs:
  - deployment: QADeploy
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
            - script: Deploy on Dev



